version: "3.7"
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=niobium
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=niobium
    ports:
      - "5432:5432"
    volumes:
      - ../data-nb-nuxt:/var/lib/postgresql/data
